services:
  baikal:
    image: ckulka/baikal
    container_name: baikal
    restart: unless-stopped

    # Never define a Docker Compose `user` configuration as it will broke the container when updating,
    # it will select by itself the user it needs

    expose:
      - 80

    volumes:
      - /srv/sync/baikal/config:/var/www/baikal/config
      - /srv/sync/baikal/specific:/var/www/baikal/Specific
    networks:
      - shared

    labels:
      - traefik.enable=true

      - traefik.http.routers.baikal-homepage.rule=Host("baikal.v.dobon.dev")

      - traefik.http.routers.baikal-admin.rule=Host("baikal.v.dobon.dev") && PathPrefix("/admin")
      - traefik.http.routers.baikal-admin.middlewares=authelia

    depends_on:
      - baikal-mariadb

  baikal-mariadb:
    image: mariadb
    container_name: baikal-mariadb
    restart: unless-stopped

    user: "${LUMINOSA_UID}:${LUMINOSA_GID}"

    expose:
      - 3306
    volumes:
      - /srv/sync/baikal/database:/var/lib/mysql
    networks:
      - shared
    environment:
      - MARIADB_DATABASE=webdav
      - MARIADB_USER=baikal
      - MARIADB_PASSWORD_FILE=/run/secrets/mariadb_password
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/mariadb_root_password
    secrets:
      - mariadb_password
      - mariadb_root_password

networks:
  shared:
    name: shared
    external: true

secrets:
  mariadb_password:
    file: ./secrets/mariadb_password.txt
  mariadb_root_password:
    file: ./secrets/mariadb_root_password.txt
