global:
  scrape_interval: 15s

scrape_configs:
    - job_name: uptime
      static_configs:
        - targets:
            - uptime-kuma:3001

    - job_name: cadvisor
      static_configs:
        - targets:
          - cadvisor:8080

    - job_name: node-exporter
      static_configs:
        - targets:
          - node-exporter:9100
