services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped

    # Never define a Docker Compose `user` configuration as it will broke the container
    # when it tries to manage its files

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Madrid
      - WATCHTOWER_SCHEDULE=0 0 5 * * *
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_NO_STARTUP_MESSAGE=true
      - WATCHTOWER_NOTIFICATION_URL=ntfy://${NTFY_USER}:${NTFY_PASSSWORD}@${NTFY_URL}/watchtower
