version: "3"

services:
  cdn:
    image: nginx
    restart: unless-stopped
    user: "0"
    expose:
      - 80
    volumes:
      - ./static/:/usr/share/nginx/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - shared
    labels:
      - traefik.enable=true

      - traefik.http.routers.cdn-router.rule=HostRegexp("{host:.+}")
      - traefik.http.routers.cdn-router.priority=1

      - traefik.http.routers.cdn-router.tls=true
      - traefik.http.routers.cdn-router.tls.certresolver=le
      - traefik.http.routers.cdn-router.tls.domains[0].main=dobon.dev
      - traefik.http.routers.cdn-router.tls.domains[0].sans=*.dobon.dev

      - traefik.http.routers.cdn-router.middlewares=cdn-middleware

      - traefik.http.middlewares.cdn-middleware.errors.status=400-599

      - traefik.http.services.cdn-service.loadbalancer.server.port=80
      - traefik.http.middlewares.cdn-middleware.errors.service=cdn-service

      - traefik.http.middlewares.cdn-middleware.errors.query=/errors/{status}/{status}.html

networks:
  shared:
    name: shared
    external: true
