version: "3"

services:
  snapdrop:
    image: lscr.io/linuxserver/snapdrop
    restart: unless-stopped
    user: "0"
    expose:
      - 3000
    volumes:
      - /srv/sync/snapdrop:/config
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Madrid
    networks:
      - shared
    labels:
      - traefik.enable=true
      - traefik.http.routers.snapdrop.rule=Host("snapdrop.dobon.dev")

      - traefik.http.routers.snapdrop.tls=true
      - traefik.http.routers.snapdrop.tls.certresolver=le
      - traefik.http.routers.snapdrop.tls.domains[0].main=dobon.dev
      - traefik.http.routers.snapdrop.tls.domains[0].sans=*.dobon.dev

networks:
  shared:
    name: shared
    external: true
