services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    restart: unless-stopped

    user: "${LUMINOSA_UID}:${LUMINOSA_GID}"

    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    expose:
      - 8384
    volumes:
      - /srv/sync/syncthing:/var/syncthing
    networks:
      - shared
    labels:
      - traefik.enable=true

      - traefik.http.services.syncthing.loadbalancer.server.port=8384
      - traefik.http.routers.syncthing.rule=Host("syncthing.v.dobon.dev")
      - traefik.http.routers.syncthing.middlewares=authelia
    environment:
      - PUID=${LUMINOSA_UID}
      - PGID=${LUMINOSA_GID}

networks:
  shared:
    name: shared
    external: true
