version: "3"

services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    restart: unless-stopped
    user: "0"
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    expose:
      - 8384
    volumes:
      - /srv/sync/syncthing:/var/syncthing
    networks:
      - shared
    labels:
      - traefik.enable=true
      - traefik.http.services.syncthing.loadbalancer.server.port=8384

      - traefik.http.routers.syncthing.rule=Host("syncthing.v.dobon.dev")

      - traefik.http.routers.syncthing.tls=true
      - traefik.http.routers.syncthing.tls.certresolver=le
      - traefik.http.routers.syncthing.tls.domains[0].main=v.dobon.dev
      - traefik.http.routers.syncthing.tls.domains[0].sans=*.v.dobon.dev

      - traefik.http.routers.syncthing.middlewares=authelia
    environment:
      - PUID=0
      - PGID=0

networks:
  shared:
    name: shared
    external: true
