services:
  cobalt-api:
    image: ghcr.io/imputnet/cobalt
    restart: unless-stopped

    # It needs root to manage its files as the image is not
    # compatible with a rootless setup
    user: "root:root"

    expose:
      - 9000
    networks:
      - shared
    labels:
      - traefik.enable=true
      - traefik.http.routers.cobalt-api.rule=Host("cobalt.dobon.dev") && PathPrefix("/api")
    environment:
      - API_PORT=9000
      - API_URL=https://cobalt.dobon.dev/
      - API_NAME=cobalt-luminosa-api

  cobalt-web:
    image: ghcr.io/imputnet/cobalt
    restart: unless-stopped

    # It needs root to manage its files as the image is not
    # compatible with a rootless setup
    user: "root:root"

    expose:
      - 9001
    networks:
      - shared
    labels:
      - traefik.enable=true
      - traefik.http.routers.cobalt-web.rule=Host("cobalt.dobon.dev")
    environment:
      - WEB_PORT=9001
      - WEB_URL=https://cobalt.dobon.dev/
      - API_URL=https://cobalt.dobon.dev/

networks:
  shared:
    name: shared
    external: true
