version: "3"

services:
  navidrome:
    image: deluan/navidrome
    restart: unless-stopped
    user: "0"
    expose:
      - 4533
    volumes:
      - ./navidrome.toml:/data/navidrome.toml:ro
      - /srv/remote/navidrome:/music:ro
      - /srv/sync/navidrome:/data
    networks:
      - shared
    labels:
      - traefik.enable=true

      - traefik.http.routers.navidrome-protected.rule=Host("navidrome.dobon.dev")

      - traefik.http.routers.navidrome-protected.tls=true
      - traefik.http.routers.navidrome-protected.tls.certresolver=le
      - traefik.http.routers.navidrome-protected.tls.domains[0].main=dobon.dev
      - traefik.http.routers.navidrome-protected.tls.domains[0].sans=*.dobon.dev

      - traefik.http.routers.navidrome-protected.middlewares=authelia

      - traefik.http.routers.navidrome-public.rule=(Host("navidrome.dobon.dev") && PathPrefix("/share")) || (Host("navidrome.dobon.dev") && PathPrefix("/rest"))

      - traefik.http.routers.navidrome-public.tls=true
      - traefik.http.routers.navidrome-public.tls.certresolver=le
      - traefik.http.routers.navidrome-public.tls.domains[0].main=dobon.dev
      - traefik.http.routers.navidrome-public.tls.domains[0].sans=*.dobon.dev
    environment:
      - ND_CONFIGFILE=/data/navidrome.toml
      - ND_PASSWORDENCRYPTIONKEY={$ND_PASSWORDENCRYPTIONKEY}
      - ND_SPOTIFY_ID={$ND_SPOTIFY_ID}
      - ND_SPOTIFY_SECRET={$ND_SPOTIFY_SECRET}
      - ND_LASTFM_APIKEY={$ND_LASTFM_APIKEY}
      - ND_LASTFM_SECRET={$ND_LASTFM_SECRET}

networks:
  shared:
    name: shared
    external: true
