{
 "title": "Docker Services",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Response Times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(monitor_name) (monitor_response_time) > -1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Containers Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(id) (rate(container_network_receive_bytes_total{id=\"/\"}[$__rate_interval]))",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "sum by(id) (rate(container_network_transmit_bytes_total{id=\"/\"}[$__rate_interval])) * -1",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "Total Containers CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[$__rate_interval])) * 100",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Total Containers Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_usage_bytes{name=~\".+\"}[$__rate_interval]))",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "Servicies Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(monitor_name) (monitor_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_memory_usage_bytes{name=~\".+\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_network_receive_bytes_total{id!=\"/\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_network_transmit_bytes_total{id!=\"/\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{name=~\".+\"}[$__rate_interval])) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}