{
 "title": "System Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "disk",
    "label": "Disk",
    "query": {
     "query": "label_values(smartmon_device_info,disk)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (\n  1 - rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])\n) * 100",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)/node_memory_MemTotal_bytes * 100",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "CPU Usage / Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg (\n  1 - rate(node_cpu_seconds_total{mode=\"idle\"}[1m])\n) * 100",
     "legendFormat": "cpu"
    },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "Critical Disks Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smartmon_reallocated_sector_ct_raw_value) or vector(0) +\r\nsum(smartmon_reported_uncorrect_raw_value) or vector(0) +\r\nsum(smartmon_command_timeout_raw_value) or vector(0) +\r\nsum(smartmon_current_pending_sector_raw_value) or vector(0) +\r\nsum(smartmon_offline_uncorrectable_raw_value) or vector(0) +\r\nsum(smartmon_reallocated_event_count_raw_value) or vector(0) +\r\nsum(smartmon_udma_crc_error_rate_raw_value) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unhealthy Disks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(smartmon_device_smart_available)-sum(smartmon_device_smart_healthy)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(device) (node_filesystem_size_bytes{mountpoint=\"/\", fstype!=\"rootfs\"} - node_filesystem_avail_bytes{mountpoint=\"/\", fstype!=\"rootfs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Disk Usage Gauge",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Selected Disk Power On Time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartmon_power_on_hours_raw_value{disk=~\"$disk\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Selected Disk Temperture",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "smartmon_temperature_celsius_raw_value{disk=~\"$disk\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}