services:
  homer:
    image: b4bz/homer
    container_name: homer
    restart: unless-stopped

    user: "${LUMINOSA_UID}:${LUMINOSA_GID}"

    expose:
      - 8080
    volumes:
      - ./assets/:/www/assets:ro
    networks:
      - shared
    labels:
      - traefik.enable=true
      - traefik.http.routers.homer.rule=Host("home.dobon.dev")

networks:
  shared:
    name: shared
    external: true
