services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    restart: unless-stopped
    
    # Needs to be root user to access the Docker socket
    user: "root:root"

    expose:
      - 3001
    volumes:
      - /srv/sync/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - shared
    labels:
      - traefik.enable=true

      - traefik.http.routers.uptime-kuma-private.rule=Host("uptime.v.dobon.dev")
      - traefik.http.routers.uptime-kuma-private.middlewares=authelia

      - traefik.http.routers.uptime-kuma-public.rule=(Host("status.dobon.dev") && Path("/")) || (Host("status.dobon.dev") && PathPrefix("/assets")) || (Host("status.dobon.dev") && PathPrefix("/api")) || (Host("status.dobon.dev") && PathPrefix("/upload"))

networks:
  shared:
    name: shared
    external: true
