services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    restart: unless-stopped

    user: "${LUMINOSA_UID}:${LUMINOSA_GID}"

    expose:
      - 80
    volumes:
      - ./server.yml:/etc/ntfy/server.yml:ro
      - /srv/sync/ntfy/user.db:/var/lib/ntfy/user.db
      - /srv/sync/ntfy/cache:/var/cache/ntfy
    networks:
      - shared
    labels:
      - traefik.enable=true
      - traefik.http.routers.ntfy.rule=Host("ntfy.v.dobon.dev")
    environment:
      - TZ=Europe/Madrid
      - WEB_PUSH_PUBLIC_KEY={$WEB_PUSH_PUBLIC_KEY}
      - WEB_PUSH_PRIVATE_KEY={$WEB_PUSH_PRIVATE_KEY}

networks:
  shared:
    name: shared
    external: true
