services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    restart: unless-stopped
    user: "0"
    ports:
      - 51820:51820/udp
    expose:
      - 51821
    volumes:
      - /srv/sync/wg-easy:/etc/wireguard
    environment:
      - LANG=en
      - WG_HOST=null.dobon.dev
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - shared

networks:
  shared:
    name: shared
    external: true
